repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    - id: isort
      language_version: python3
      types: [file, python]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3
      args: [--safe, --quiet]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell
        args: [-L nnumber]
        exclude: /.*\.txt
-   repo: https://github.com/luismayta/pre-commit-mypy
    rev: 0.1.1
    hooks:
    -   id: mypy
        additional_dependencies:
        - pydantic
        - types-requests
        - types-PyYAML
        args: [--ignore-missing-imports]
